<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Libraries used by Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!--Font awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!--Custom css-->
    <link rel="stylesheet" href="/assets/css/custom-css.css">

    <title>Candidate - Quizzes listing</title>
</head>

<body>
    <!--Header-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 mb-3 bg-light border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Toni's Quiz App</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <span class="p-2 text-dark">Hello, <?php echo $name ?>!</span>
        </nav>
        <a class="btn btn-danger" href="/logout">Logout</a>
    </div>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item active" aria-current="page"><a href="/">Dashboard</a></li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Quizzes</h1>
        </div>

        <!--Quizzes listing-->
        <table class="table table-hover my-4">
            <thead>
            <tr>
                <th scope="col">Quiz name</th>
                <th scope="col">Description</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data as $datum) :?>
            <tr>
                <th scope="row"><?php echo $datum->getName() ?></th>
                <td> <?php echo $datum->getText() ?> </td>
                <td class="text-center">
                    <a class="btn btn-primary py-1" href="/user/quiz/<?php echo $datum->getID()?>">Start quiz</a>
                </td>
            </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>

    <!--Pagination block-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <?php if ($page == 1): ?>
                <li class="page-item disabled">
                    <a class="page-link" href="" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
            <?php else: ?>
                <li class="page-item">
                    <a class="page-link" href="/user?search=<?php echo $search ?>&page=<?php echo $page-1 ?>" tabindex="-1" >Previous</a>
                </li>
            <?php endif ?>

            <?php for($i = 1; $i <= $count; $i++):?>

                <?php if ($i == $page): ?>
                    <li class="page-item active"><a class="page-link" href="/user?search=<?php echo $search ?>&page=<?php echo $i ?>"><?php echo $i ?></a></li>
                <?php else: ?>
                    <li class="page-item"><a class="page-link" href="/user?search=<?php echo $search ?>&page=<?php echo $i ?>"><?php echo $i ?></a></li>
                <?php endif ?>
            <?php endfor ?>

            <?php if ($page == $count || $count <= 1.0 ): ?>
                <li class="page-item disabled">
                    <a class="page-link" href="" tabindex="-1" aria-disabled="true">Next</a>
                </li>
            <?php else: ?>
                <li class="page-item">
                    <a class="page-link" href="/user?search=<?php echo $search ?>&page=<?php echo $page+1 ?>" tabindex="-1" >Next</a>
                </li>
            <?php endif ?>
        </ul>
    </nav>

</body>
</html>